"""
AudioFile model - Generated audio files.
"""

from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.types import UUID
from app.database import Base
import uuid


class AudioFile(Base):
    """
    Generated audio file.
    
    Stores metadata about audio files generated by the provider.
    Usually 2 versions per generation.
    """
    __tablename__ = "audio_files"
    
    id = Column(
        UUID(),
        primary_key=True,
        default=uuid.uuid4
    )
    job_id = Column(UUID(), ForeignKey("generation_jobs.id", ondelete="CASCADE"), nullable=False)
    project_id = Column(UUID(), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    
    file_path = Column(String, nullable=False)  # Local or storage path
    file_url = Column(String, nullable=True)    # Download URL
    stream_url = Column(String, nullable=True)  # Stream URL
    image_url = Column(String, nullable=True)   # Cover image URL
    
    duration = Column(Integer, nullable=True)   # Duration in seconds
    version_number = Column(Integer, nullable=False, default=1)  # 1 or 2
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    
    def __repr__(self):
        return f"<AudioFile {self.id} - v{self.version_number}>"
